package jcaster_vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class Gui extends CustomComponent {

	private static final long serialVersionUID = -1611052336777678930L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_1;
	@AutoGenerated
	private MenuBar menuBar_1;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Gui() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		
		// top-level component properties
		setWidth("400px");
		setHeight("300px");
		
		// absoluteLayout_1
		absoluteLayout_1 = buildAbsoluteLayout_1();
		mainLayout.addComponent(absoluteLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_1() {
		// common part: create layout
		absoluteLayout_1 = new AbsoluteLayout();
		absoluteLayout_1.setWidth("100.0%");
		absoluteLayout_1.setHeight("20px");
		absoluteLayout_1.setImmediate(false);
		absoluteLayout_1.setMargin(false);
		
		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setWidth("100.0%");
		menuBar_1.setHeight("100.0%");
		menuBar_1.setImmediate(false);
		MenuBar.MenuItem fileMenu =
			menuBar_1.addItem("File", null, null);
		MenuBar.MenuItem helpMenu =
			menuBar_1.addItem("Help", null, null);
		helpMenu.addItem("Help", null, null);
		helpMenu.addItem("About", null, null);
		absoluteLayout_1.addComponent(menuBar_1);
		
		return absoluteLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("20px");
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setMargin(false);
		
		// button_1
		button_1 = new Button();
		button_1.setWidth("100.0%");
		button_1.setHeight("50px");
		button_1.setCaption("Record");
		button_1.setImmediate(true);
		horizontalLayout_2.addComponent(button_1);
		
		// button_2
		button_2 = new Button();
		button_2.setWidth("100.0%");
		button_2.setHeight("50px");
		button_2.setCaption("Pause");
		button_2.setImmediate(true);
		horizontalLayout_2.addComponent(button_2);
		
		// button_3
		button_3 = new Button();
		button_3.setWidth("100.0%");
		button_3.setHeight("50px");
		button_3.setCaption("Stop");
		button_3.setImmediate(true);
		horizontalLayout_2.addComponent(button_3);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("100.0%");
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setMargin(false);
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		horizontalLayout_3.addComponent(tabSheet_1);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		tabSheet_1.setImmediate(true);
		
		// panel_1
		panel_1 = buildPanel_1();
		tabSheet_1.addTab(panel_1, "General settings", null);
		
		// panel_2
		panel_2 = buildPanel_2();
		tabSheet_1.addTab(panel_2, "Video settings", null);
		
		// panel_3
		panel_3 = buildPanel_3();
		tabSheet_1.addTab(panel_3, "Audio settings", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		panel_1.setImmediate(false);
		
		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setMargin(false);
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setWidth("100.0%");
		panel_2.setHeight("100.0%");
		panel_2.setImmediate(false);
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setMargin(false);
		panel_2.setContent(verticalLayout_3);
		
		return panel_2;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setWidth("100.0%");
		panel_3.setHeight("100.0%");
		panel_3.setImmediate(false);
		
		// verticalLayout_4
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setMargin(false);
		panel_3.setContent(verticalLayout_4);
		
		return panel_3;
	}

}
